[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/highend/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    127.0.0.1
    10.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    100.64.0.0/10

cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://127.0.0.1
    *://192.168.0.14
    *://192.168.0.5
    *://100.64.245.120
    *://my.mainsail.xyz
    *://app.fluidd.xyz
    *://bttpi2.local:7136
    *://bttpi2.local:7912
    
[octoprint_compat]
[history]
#[annunciator]
#[shaketune]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
path: /home/highend/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/highend/mainsail-config
primary_branch: master
type: git_repo

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[timelapse]
output_path: ~/printer_data/timelapse/
frame_path: /tmp/timelapse/printer

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[spoolman]
server: http://localhost:7912
sync_rate: 30

[update_manager led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False

[power printer]
type: klipper_device
object_name: output_pin PS_ON
locked_while_printing: True
initial_state: on

[update_manager fluidd]
path: /home/highend/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web
persistent_files:
    config.json

[update_manager mobileraker]
install_script: /home/highend/mobileraker_companion/scripts/install.sh
requirements: /home/highend/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/highend/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/highend/mobileraker_companion
type: git_repo

[announcements]
subscriptions:
    mobileraker

[update_manager pgcode]
type: git_repo
primary_branch: main
origin: https://github.com/Kragrathea/pgcode.git
path: ~/pgcode
is_system_service: False

[update_manager klipper_tmc_autotune]
primary_branch: main
managed_services: klipper
origin: https://github.com/andrewmcgr/klipper_tmc_autotune
path: /home/highend/klipper_tmc_autotune
channel: dev
type: git_repo


[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main
